### ISSUE TITLE
Limitations to acquiring data over one year ago?

### ISSUE THREAD

**Issue by anoduck** [gmchad/otterai-api#2]
I cannot express my thanks for creating this api. Accessing Otter programmatically will allow me to establish the existence of events that have had quite a significant impact on my life. 

I was wondering, since you have already taken the dive into the unknown, if there is anything preventing me from acquiring data from over a year ago? Right now, I can access up to Jan 2023, but I need to reach further.

Cheers.

**Comment by anoduck** [comment]
Ooops... Look at that! The variable `page_size` controls the amount of entries to pull. Well, isn't that nice.

**Comment by ShayanYasir** [comment]
Hey @anoduck , did you get any 504 timeout codes? Currently trying to download 1000+ conversations and can't get to 500 without it timing out on me. Thoughts?

**Comment by anoduck** [comment]
@ShayanYasir You are probably hitting a rate limit trigger and the application firewall is intentionally letting your connection attempts timeout. Try to incorporate [tenacity](https://github.com/jd/tenacity) into your script and/or use a simple `time.sleep(random.uniform(0.27, 4.3))`. I have used both to circumvent rate-limiting.

**Comment by ShayanYasir** [comment]
Thank you @anoduck. I appreciate your help with this, everything works perfectly now.

**Comment by ShayanYasir** [comment]
Hey @anoduck , actually looks like my solution isn't really working, mind sharing how you implemented this into the `get_speeches` method? I can only load about 500 speeches with the addition of `time.sleep(random.uniform(0.27, 4.3)` before I get rate-limited

**Comment by anoduck** [comment]
@ShayanYasir You might need to break down the amount you download at one time into smaller "sets", and then space out your "sets" by however long it takes for the rate limitation to expire. The latter will have to be discovered by trial and error.

[JobFunnel](https://github.com/anoduck/JobFunnel/blob/master/jobfunnel/backend/tools/delay.py), which I did do some work on, has an absolutely brilliant solution to this. Much more elaborate than what I have implemented on my own. 

[UFS-quackified](https://github.com/anoduck/UFS-quackified/blob/Master/scraper/photo-scrape.py) may not be OtterAPI specific and is the first script I ever wrote (no judging), but it uses a similar convention. That is, to use a `sleep(randint(1, 9999))` at the end of each request loop. 

[Piotr](https://codeberg.org/anoduck/piotr) is the work I have done on Otter API. It is a mess, but at the time of writing it, I was too busy to care. The function of it is completely different from what you are working on, and it does not download speeches yet, but it may prove to be useful. 

I will open up Piotr in my IDE and work on adding download functionality. It is something I need to do in order to complete a current project. I will see what issues I encounter.

**Comment by anoduck** [comment]
@ShayanYasir Once, I used the ID located within the "download_url", rather than the actually "speech_id", it worked like a top. 

I was able to download 558 speeches without a hitch or encountering any error messages. So, I am not sure what is going on.

**Comment by ShayanYasir** [comment]
@anoduck appreciate the help, will take a look. I think I was just having trouble with batching requests, going to use the scripts you provided to hopefully figure this out.

**Comment by anoduck** [comment]
@ShayanYasir Just take a look at [piotr](https://codeberg.org/anoduck/piotr), more specifically `piotr/down.py`. 

After writing my own script to download speeches, I believe your best bet is to break down the number of speeches you attempt to download at one time into groups of 500 or less, and then insert a `sleep(randint(1, 270))` between each group. Otterai-api does not provide robust exception handling, so using libraries like "retrying" will not work well.

Error code 403 is difficult to diagnose. I wish you the best of luck.
